image: "tmaric/openfoam-v2012_ubuntu-focal:latest"

stages:
  - building

build:
  stage: building
  script:

    ##
    ## Configure the OpenFOAM environment
    ##
    - source /opt/OpenFOAM/OpenFOAM-v2012/etc || true  

    ##
    ## Build and install: this project only has a single OF application
    ##
    - ./Allwmake 

    ##
    ## OpenFOAM stores app and library binaries outside of project folder!
    ## To re-use project apps and libraries, use FOAM_USER_* env variables.
    ## Store the app and library binary files in a local folder and forward
    ## this folder to the next job using GitLab CI artifacts. 
    ##
   
    ## 
    ## Uncomment if the project builds user-defined OF libraries. 
    ##
    - mkdir FOAM_USER_LIBBIN && cp $FOAM_USER_LIBBIN/* FOAM_USER_LIBBIN
    - mkdir FOAM_USER_APPBIN && cp $FOAM_USER_APPBIN/* FOAM_USER_APPBIN

  artifacts:
    paths:

        ##
        ## Uncomment if user-defind OF libraries are built.
        ##
        - FOAM_USER_LIBBIN/*
       
        ##
        ## Export user-defined OF applications
        ##
        - FOAM_USER_APPBIN/*
