#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -r 0.org 0
runApplication blockMesh
runApplication foamSetRotationalPatchVelocity  -axisPoint '(0 0 0)' -angularVelocity '(0 0 1)' -patchName innerWall
runApplication decomposePar

mpirun -np 4 $(getApplication) -parallel # local mpi parallel run
#runParallel $(getApplication) # local mpi parallel run in background
#runApplication $(getApplication) # serial run

#------------------------------------------------------------------------------
