#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf 0 && cp -r 0.org 0 
runApplication blockMesh
runApplication decomposePar

# Serial run in background
#runApplication $(getApplication) 

# Local MPI run in background 
#runParallel $(getApplication) 

# Local MPI run in foreground (parameter study)
mpirun -np 4 $(getApplication) \
    -parallel 2>&1 | tee log.$(getApplication) 

#------------------------------------------------------------------------------
