#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf convergence-study*/

rm -rf *.variations 

rm -rf *.database

rm -rf log.*

rm -rf *.csv

rm -rf *.pdf

#------------------------------------------------------------------------------
