#!/usr/bin/env python3
"""LaTeX tables of a method gate for the pre-print (CLAUDE.md "Method gates").

Reads studies/<gate>_summary/<candidate>/{summary,orders}.csv and verdict.txt (written by
make_gate_summary.py) and writes, into --out:

  <gate>_verdicts.tex   one row per candidate: the verdict, the target ratio, the number of
                        regression, order and seam failures, and the completion state;
  <gate>_<arm>.tex      one table per arm: per candidate the value at the finest rung and the
                        least-squares order of each metric of that arm (L2 and L1 norms only).

Usage:
  make_gate_tables.py --summary-root studies/methodGate2D_summary --gate methodGate2D \\
      --out docs/gradient-controlled-level-set/gcls-level-set-article/data/tables
"""
import argparse
import csv
import os
import re

# The metrics of each arm, in the order of the table columns (L2 and L1 norms only).
ARM_METRICS = {
    "shear":       ["gradientBandError", "shapeError", "volumeError", "volumeErrorHalf"],
    "stationary":  ["gradientBandError", "l2MagUPrime", "pressureJumpError", "curvatureError", "volumeError"],
    "translating": ["gradientBandError", "travelledFractionError", "shapeError", "l2MagUPrime", "volumeError"],
    "oscillating": ["gradientBandError", "volumeError", "l2MagUPrime"],
}
LABEL = {
    "gradientBandError": r"$\lVert q-1\rVert_{2,\mathrm{band}}$",
    "shapeError": r"$e_\mathrm{shape}$",
    "volumeError": r"$e_V(T)$",
    "volumeErrorHalf": r"$e_V(T/2)$",
    "l2MagUPrime": r"$\lVert\mathbf u'\rVert_2$",
    "pressureJumpError": r"$e_{\Delta p}$",
    "curvatureError": r"$e_\kappa$",
    "travelledFractionError": r"$e_\mathrm{travel}$",
}


def read_csv(path):
    if not os.path.isfile(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def fmt(v, order=False):
    if v is None:
        return "--"
    if order:
        return f"{v:.2f}"
    return r"\num{" + f"{v:.2e}" + "}"


def tex_escape(s):
    return s.replace("_", r"\_")


def candidates_of(root):
    names = sorted(d for d in os.listdir(root) if os.path.isfile(os.path.join(root, d, "summary.csv")))
    for b in ("baselineEulerian", "baseline"):
        if b in names:
            names.remove(b)
            names.insert(0, b)
    return names


def verdict_row(root, cand):
    path = os.path.join(root, cand, "verdict.txt")
    if not os.path.isfile(path):
        return {"verdict": "reference" if cand.startswith("baseline") else "--"}
    lines = open(path).read().splitlines()
    first = lines[0] if lines else ""
    m = re.search(r"VERDICT (PASS|FAIL|INVALID)", first)
    row = {"verdict": m.group(1) if m else "--",
           "regressions": sum(l.startswith("FAIL regression") for l in lines),
           "orders": sum(l.startswith("FAIL order") for l in lines),
           "seam": sum(l.startswith("FAIL seam") for l in lines),
           "completion": sum(l.startswith("FAIL completion") for l in lines),
           "noEffect": any(l.startswith("FAIL no effect") for l in lines)}
    t = [l for l in lines if " target: " in l]
    ratios = [re.search(r"ratio ([0-9.eE+-]+)", l) for l in t]
    row["target"] = ", ".join(r.group(1) for r in ratios if r) or "--"
    return row


def write_verdicts(root, gate, out):
    rows = []
    for c in candidates_of(root):
        v = verdict_row(root, c)
        rows.append(" & ".join([
            r"\texttt{" + tex_escape(c) + "}", v["verdict"], v.get("target", "--"),
            str(v.get("regressions", "--")), str(v.get("orders", "--")), str(v.get("seam", "--")),
            str(v.get("completion", "--"))]) + r"\\")
    body = "\n".join(rows)
    tex = rf"""% Generated by workflow/scripts/make_gate_tables.py from studies/{gate}_summary; do not edit.
\begin{{tabular}}{{lllrrrr}}
  \toprule
  candidate & verdict & target ratio & regressions & order & seam & completion\\
  \midrule
{body}
  \bottomrule
\end{{tabular}}
"""
    open(os.path.join(out, f"{gate}_verdicts.tex"), "w").write(tex)


def write_arm(root, gate, arm, out):
    metrics = ARM_METRICS[arm]
    lines = []
    finestN = None
    for c in candidates_of(root):
        summ = [r for r in read_csv(os.path.join(root, c, "summary.csv")) if r.get("arm") == arm]
        if not summ:
            continue
        fin = min(summ, key=lambda r: num(r.get("h")) or 1e300)
        finestN = fin.get("N")
        orders = {r["metric"]: num(r.get("lsqOrder")) for r in read_csv(os.path.join(root, c, "orders.csv"))
                  if r.get("arm") == arm}
        cells = [r"\texttt{" + tex_escape(c) + "}"]
        for m in metrics:
            cells += [fmt(num(fin.get(m))), fmt(orders.get(m), order=True)]
        lines.append(" & ".join(cells) + r"\\")
    if not lines:
        return
    head = " & ".join(r"\multicolumn{2}{c}{" + LABEL[m] + "}" for m in metrics)
    sub = " & ".join(["value & order"] * len(metrics))
    cmid = " ".join(rf"\cmidrule(lr){{{2 + 2*i}-{3 + 2*i}}}" for i in range(len(metrics)))
    body = "\n".join(lines)
    tex = rf"""% Generated by workflow/scripts/make_gate_tables.py from studies/{gate}_summary; do not edit.
% Arm {arm}: the value at the finest rung (N = {finestN}) and the least-squares order over the rungs.
\begin{{tabular}}{{l{'rr' * len(metrics)}}}
  \toprule
  & {head}\\
  {cmid}
  candidate & {sub}\\
  \midrule
{body}
  \bottomrule
\end{{tabular}}
"""
    open(os.path.join(out, f"{gate}_{arm}.tex"), "w").write(tex)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--summary-root", required=True)
    ap.add_argument("--gate", required=True, help="the gate name used in the file names")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    write_verdicts(a.summary_root, a.gate, a.out)
    for arm in ARM_METRICS:
        write_arm(a.summary_root, a.gate, arm, a.out)
    print(f"[gate-tables] {a.gate}: tables in {a.out}")


if __name__ == "__main__":
    main()
