#!/usr/bin/env python3
"""Curated table of the capillary flux-residual gate (WP8.0).

Reads the per-corrector capillaryFluxResidual.csv (written by pEqn.H) and the
droplet metrics CSV of each arm of the gate -- delivery x pressure algebra --
and emits into the semi-Lagrangian theme's data source:

    data/tables/capillary_flux_residual.csv   one row per arm
    data/tables/capillary_flux_residual.tex   booktabs body (\\input by the article)

Columns per arm: the non-absorbable fraction max|R_f|/max|phig| on the active
snGrad(alpha) faces at the first step and as the run median, the velocity
residual fvc::reconstruct produces from R_f, the peak parasitic velocity, and
the pressure-solver work (median iterations and final residual) that produced
those numbers.

Usage (from repo root):
    python3 workflow/scripts/make_capillary_residual_table.py \\
        "label=runs/wp80_arith_gamg" ["label=..." ...]
"""
import csv
import os
import statistics
import sys

import paths

THEME = "semi-lagrangian-level-set"
RES = "capillaryFluxResidual.csv"
MET = "leiaSemiLagrangianLevelSetTwoPhaseFoam.csv"


def _rows(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))


def main(argv):
    if not argv:
        print(__doc__)
        return 1

    recs = []
    for spec in argv:
        label, case = spec.rsplit("=", 1)
        r = _rows(os.path.join(case, RES))
        if not r:
            print(f"[caprad] {case}: empty {RES}, skipped")
            continue
        f = lambda k: [float(x[k]) for x in r]
        m = [x for x in _rows(os.path.join(case, MET)) if x.get("maxMagU")]
        recs.append({
            "arm": label,
            "fracMax_t0": float(r[0]["RfFracMax"]),
            "fracMax_median": statistics.median(f("RfFracMax")),
            "fracL2_median": statistics.median(f("RfFracL2")),
            "maxUres_t0": float(r[0]["maxUresidual"]),
            "maxUres_end": float(r[-1]["maxUresidual"]),
            "maxU_peak": max(float(x["maxMagU"]) for x in m) if m else "",
            "pIterations_median": statistics.median(f("pIterations")),
            "pFinalResidual_median": statistics.median(f("pFinalResidual")),
            "t_end": float(r[-1]["TIME"]),
        })
        print(f"[caprad] {label}: frac {recs[-1]['fracMax_t0']:.3e} -> median "
              f"{recs[-1]['fracMax_median']:.3e}, p iters "
              f"{recs[-1]['pIterations_median']:.0f}")

    if not recs:
        return 1
    tables = paths.tables_dir(THEME)

    cpath = os.path.join(tables, "capillary_flux_residual.csv")
    with open(cpath, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(recs[0]))
        w.writeheader(); w.writerows(recs)
    print(f"[caprad] wrote {cpath} ({len(recs)} rows)")

    tpath = os.path.join(tables, "capillary_flux_residual.tex")
    with open(tpath, "w") as fh:
        fh.write("% Auto-generated by workflow/scripts/"
                 "make_capillary_residual_table.py -- do not edit.\n")
        fh.write("\\begin{tabular}{lccccc}\n\\toprule\n")
        fh.write("arm & $R_f/G_{\\sigma}$ at $t_0$ & median & "
                 "$\\max|\\uvec_{\\mathrm{res}}|$ at $t_0$ & "
                 "peak $\\max|\\uvec|$ & $p$ final residual (med.) \\\\\n\\midrule\n")
        for r in recs:
            fh.write(f"{r['arm']} & {r['fracMax_t0']:.2e} & "
                     f"{r['fracMax_median']:.2e} & {r['maxUres_t0']:.2e} & "
                     f"{r['maxU_peak']:.2e} & "
                     f"{r['pFinalResidual_median']:.1e} \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print(f"[caprad] wrote {tpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
