#!/usr/bin/env python3
"""Flux-form vs point-value SL volume-loss mechanism figure (reversed vortex,
T = 8, N = 128). Reads the committed time series
data/tables/flux_volloss_timeseries.csv (regenerated by the diagnostic run) and
plots, side by side:
  - relative phase-volume change dV/V0(t): flux-form loses MONOTONICALLY
    (irreversible upwind-FV dissipation), point-value oscillates and RECOVERS
    (reversible dispersive error);
  - band mean |grad psi|(t): flux-form flattens below 1 (smeared interface),
    point-value stays steeper.

    python3 make_flux_volloss_fig.py
"""
import csv
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import paths

THEME = "method-comparison"


def main():
    tdir = paths.tables_dir(THEME, make=False)
    src = os.path.join(tdir, "flux_volloss_timeseries.csv")
    if not os.path.isfile(src):
        print(f"[flux_volloss] no {src}; run the diagnostic first")
        return
    t, pvV, pvG, fxV, fxG = [], [], [], [], []
    for r in csv.DictReader(open(src)):
        t.append(float(r["t"]))
        pvV.append(float(r["pv_dVrel"])*100); fxV.append(float(r["flux_dVrel"])*100)
        pvG.append(float(r["pv_bandGrad"]));  fxG.append(float(r["flux_bandGrad"]))

    fig, ax = plt.subplots(1, 2, figsize=(11, 4.6))
    ax[0].axhline(0, color="k", lw=0.6, alpha=0.5)
    ax[0].plot(t, pvV, "o-", label="point-value SL")
    ax[0].plot(t, fxV, "s--", label="flux-form SL")
    ax[0].set_xlabel("t"); ax[0].set_ylabel(r"$\Delta V/V_0$  [%]")
    ax[0].set_title("phase volume: flux LOSES monotonically,\n"
                    "point-value oscillates + recovers", fontsize=10)
    ax[0].grid(True, alpha=0.25); ax[0].legend(fontsize=8)

    ax[1].axhline(1, color="k", lw=0.6, alpha=0.5)
    ax[1].plot(t, pvG, "o-", label="point-value SL")
    ax[1].plot(t, fxG, "s--", label="flux-form SL")
    ax[1].set_xlabel("t"); ax[1].set_ylabel(r"band mean $|\nabla\psi|$")
    ax[1].set_title("interface gradient: flux flattens (dissipation)\n"
                    "esp. under sub-cell compression (peak ~t=3)", fontsize=10)
    ax[1].grid(True, alpha=0.25); ax[1].legend(fontsize=8)

    fig.suptitle("Where the flux-form volume loss comes from "
                 "(reversed vortex, N = 128, T = 8)", fontsize=11)
    fig.tight_layout()
    out = os.path.join(paths.figs_dir(THEME), "benchVortex_fluxvolloss.png")
    fig.savefig(out, dpi=200); plt.close(fig)
    print(f"[flux_volloss] wrote {out}")


if __name__ == "__main__":
    main()
