#!/usr/bin/env python3
"""Fuse table of the coupled stationary-droplet gates: for each case, the
runaway ONSET (first max|U| crossing of 0.1 m/s -- unambiguous on a benchmark
whose exact velocity is zero), the BLOW-UP time (first crossing of 10 m/s, the
evolution figure's cap), and the final state, from the per-step droplet CSV.

Usage:
    python3 workflow/scripts/make_droplet_fuse_table.py "label=case" [...]

Emits droplet_fuse.csv + droplet_fuse.tex into the method-comparison theme's
data/tables (the coupled follow-up of the face-centered curvature gate).
"""
import csv
import os
import sys

import paths

THEME = "method-comparison"
CSV_NAME = "leiaSemiLagrangianLevelSetTwoPhaseFoam.csv"
ONSET, BLOWUP = 0.1, 10.0


def _trace(case):
    t, u = [], []
    with open(os.path.join(case, CSV_NAME), newline="") as fh:
        for row in csv.DictReader(fh):
            try:
                ti, ui = float(row["TIME"]), float(row["maxMagU"])
            except (TypeError, ValueError, KeyError):
                continue
            t.append(ti); u.append(ui)
    return t, u


def _first_crossing(t, u, th):
    for ti, ui in zip(t, u):
        if ui > th:
            return ti
    return None


def main(argv):
    if not argv:
        print(__doc__)
        return 1
    rows = []
    for spec in argv:
        label, case = spec.rsplit("=", 1)
        t, u = _trace(case)
        if not t:
            print(f"[fuse] {case}: no rows, skipped")
            continue
        on = _first_crossing(t, u, ONSET)
        bl = _first_crossing(t, u, BLOWUP)
        # Final max|U| only meaningful for runs that stayed physical.
        end_u = u[-1] if u[-1] <= BLOWUP else None
        rows.append({
            "label": label, "t_end": t[-1],
            "onset_t": on, "blowup_t": bl,
            "maxU_end": end_u,
            "survived": (on is None),
        })
        print(f"[fuse] {label}: t_end={t[-1]:.4g} onset={on} blowup={bl} "
              f"endU={end_u}")

    tables = paths.tables_dir(THEME)

    cpath = os.path.join(tables, "droplet_fuse.csv")
    with open(cpath, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader(); w.writerows(rows)
    print(f"[fuse] wrote {cpath} ({len(rows)} rows)")

    tpath = os.path.join(tables, "droplet_fuse.tex")
    with open(tpath, "w") as fh:
        fh.write("% Auto-generated by workflow/scripts/make_droplet_fuse_table.py"
                 " -- do not edit.\n")
        fh.write("\\begin{tabular}{lcccc}\n\\toprule\n")
        fh.write("run & horizon [s] & onset $\\max|U|{>}0.1$ & blow-up "
                 "${>}10$ & final $\\max|U|$ [m/s] \\\\\n\\midrule\n")
        for r in rows:
            on = f"{r['onset_t']:.4f}" if r["onset_t"] is not None else "--"
            bl = f"{r['blowup_t']:.4f}" if r["blowup_t"] is not None else "--"
            eu = f"{r['maxU_end']:.2e}" if r["maxU_end"] is not None else "diverged"
            fh.write(f"{r['label']} & {r['t_end']:.3g} & {on} & {bl} & {eu} \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print(f"[fuse] wrote {tpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
