#!/usr/bin/env python3
"""Materialize one study variation into a runnable OpenFOAM case directory.

Steps:
  1. copy the template case (``cases/<Case>``) into the study output dir,
  2. render every ``*.template`` by replacing ``@!TOKEN!@`` with the variation's
     value (``$aliases`` are kept verbatim for OpenFOAM to expand at run time),
     then drop the ``.template`` suffix and delete the template file,
  3. regenerate ``system/decomposeParDict`` from ``np`` (so the rank count and
     the decomposition can never disagree),
  4. write a ``case_params.json`` sidecar (the parameter vector + metadata),
  5. abort if any unsubstituted ``@!...!@`` token remains.
"""
import json
import os
import re
import shutil

_TOKEN = re.compile(r"@!([A-Z0-9_]+)!@")
_IGNORE = shutil.ignore_patterns(
    "processor*", "*.foam", "postProcessing", "*.csv", "log", "log.*",
    "out.*", "err.*", "case_params.json")

# Frozen exact-circle pressure-potential velocity convergence on deterministic
# 10%-perturbed N=32,64,128 meshes is unchanged between 8,16,32,64 corrected
# passes.  Never let a general perturbed-mesh study silently inherit the
# uniform-mesh default of one correction.
_MIN_PERTURBED_NONORTHOGONAL_CORRECTORS = 8


def _render_templates(case_dir, tokens):
    for root, _dirs, files in os.walk(case_dir):
        for f in list(files):
            if not f.endswith(".template"):
                continue
            src = os.path.join(root, f)
            with open(src) as fh:
                text = fh.read()
            for key, val in tokens.items():
                text = text.replace(f"@!{key}!@", str(val))
            with open(os.path.join(root, f[:-len(".template")]), "w") as fh:
                fh.write(text)
            os.remove(src)


def _write_decompose_par_dict(case_dir, np_):
    """Scotch decomposition: only ``numberOfSubdomains`` is needed -- scotch
    partitions the cell connectivity graph, so there are no per-direction coeffs
    to keep consistent and it works for any ``np`` and any (2D/3D) mesh."""
    text = (
        "/*--------------------------------*- C++ -*"
        "----------------------------------*\\\n"
        f"| generated by the leia Snakemake workflow (np={np_}, scotch)\n"
        "\\*--------------------------------------------------------------------"
        "-------*/\n"
        "FoamFile\n{\n    version     2.0;\n    format      ascii;\n"
        "    class       dictionary;\n    object      decomposeParDict;\n}\n"
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * "
        "* * * //\n\n"
        f"numberOfSubdomains {np_};\n\nmethod          scotch;\n\n"
        "// ********************************************************************"
        "***** //\n")
    system_dir = os.path.join(case_dir, "system")
    os.makedirs(system_dir, exist_ok=True)
    with open(os.path.join(system_dir, "decomposeParDict"), "w") as fh:
        fh.write(text)


def _assert_no_residual_tokens(case_dir):
    bad = []
    for root, _dirs, files in os.walk(case_dir):
        for f in files:
            path = os.path.join(root, f)
            try:
                with open(path, encoding="utf-8", errors="ignore") as fh:
                    if _TOKEN.search(fh.read()):
                        bad.append(os.path.relpath(path, case_dir))
            except OSError:
                continue
    if bad:
        raise SystemExit(f"[materialize] unsubstituted @!TOKEN!@ remain in: {bad}")


def _with_derived_tokens(tokens):
    """Add tokens that are computed from the sweep values, so templates can use
    them directly:

      * HALF_END_TIME = END_TIME/2 -- controlDict writes a snapshot at maximum
        deformation (t = T/2) as well as t = 0 and t = T (advection studies).
      * MAX_DELTA_T uses one of two explicit modes selected by
        TIME_STEP_CONTROL:

          capillary: CAPILLARY_DT_COEFF / N_CELLS^1.5
          advective: TARGET_ADVECTIVE_CO*DOMAIN_LENGTH /
                     (N_CELLS*REFERENCE_SPEED)

        The capillary mode remains the default for coupled surface-tension runs.
        The advective mode is for sigma=0 kinematic convergence tests, where
        retaining the capillary limit would add progressively more unnecessary
        point-value remaps and confound the spatial study."""
    out = dict(tokens)
    if "END_TIME" in out:
        try:
            out["HALF_END_TIME"] = "{:g}".format(float(out["END_TIME"]) / 2.0)
        except (TypeError, ValueError):
            pass
    time_step_control = out.get("TIME_STEP_CONTROL", "capillary")
    if time_step_control == "advective":
        required = (
            "N_CELLS",
            "TARGET_ADVECTIVE_CO",
            "DOMAIN_LENGTH",
            "REFERENCE_SPEED",
        )
        missing = [key for key in required if key not in out]
        if missing:
            raise SystemExit(
                "[materialize] advective TIME_STEP_CONTROL requires: "
                + ", ".join(missing)
            )
        try:
            n = float(out["N_CELLS"])
            co = float(out["TARGET_ADVECTIVE_CO"])
            length = float(out["DOMAIN_LENGTH"])
            speed = float(out["REFERENCE_SPEED"])
            if n <= 0 or co <= 0 or length <= 0 or speed <= 0:
                raise ValueError("all advective timestep inputs must be positive")
            out["MAX_DELTA_T"] = "{:.10g}".format(co * length / (n * speed))
        except (TypeError, ValueError) as exc:
            raise SystemExit(f"[materialize] invalid advective timestep: {exc}")
    elif time_step_control == "capillary" and "N_CELLS" in out and "CAPILLARY_DT_COEFF" in out:
        try:
            n = float(out["N_CELLS"])
            coeff = float(out["CAPILLARY_DT_COEFF"])
            if n > 0:
                out["MAX_DELTA_T"] = "{:.6g}".format(coeff / n**1.5)
        except (TypeError, ValueError):
            pass
    elif time_step_control != "capillary":
        raise SystemExit(
            "[materialize] TIME_STEP_CONTROL must be capillary or advective, got "
            + repr(time_step_control)
        )
    return out


def materialize(base_case, tokens, out_dir, np_, mesh, mode, dims, case_name, index):
    tokens = _with_derived_tokens(tokens)
    if mesh == "perturbed" and "N_NON_ORTHOGONAL_CORRECTORS" in tokens:
        try:
            current = int(tokens["N_NON_ORTHOGONAL_CORRECTORS"])
        except (TypeError, ValueError) as exc:
            raise SystemExit(
                "[materialize] N_NON_ORTHOGONAL_CORRECTORS must be an integer: "
                + str(exc)
            )
        tokens["N_NON_ORTHOGONAL_CORRECTORS"] = str(
            max(current, _MIN_PERTURBED_NONORTHOGONAL_CORRECTORS)
        )
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    shutil.copytree(base_case, out_dir, ignore=_IGNORE)
    _render_templates(out_dir, tokens)
    _write_decompose_par_dict(out_dir, np_)
    _assert_no_residual_tokens(out_dir)
    meta = {
        "case": case_name, "mesh": mesh, "mode": mode, "np": int(np_),
        "dims": dims, "index": index, "tokens": dict(tokens),
    }
    with open(os.path.join(out_dir, "case_params.json"), "w") as fh:
        json.dump(meta, fh, indent=2)
    # ParaView case marker: an empty ``<caseName>.foam`` lets the OpenFOAM reader
    # open this study case directly (File > Open <caseName>.foam). One per case, in
    # the results dir, named after the case so it is identifiable in the file dialog.
    open(os.path.join(out_dir, f"{case_name}.foam"), "w").close()
    return meta
