#!/usr/bin/env python3
"""Materialize one study variation into a runnable OpenFOAM case directory.

NOTE ON ERROR TYPE. Every failure here raises RuntimeError, never SystemExit.
This module is imported and called from a snakemake ``run:`` block, which
executes in-process: a SystemExit there terminates the worker instead of
propagating, and the parent then blocks on a futex forever. A single missing
token reference produced a silent 4.5-hour deadlock on the cluster before this
was changed -- the configuration error was correct and clean, only the way it was
raised was not.

Steps:
  1. copy the template case (``cases/<Case>``) into the study output dir,
  2. render every ``*.template`` by replacing ``@!TOKEN!@`` with the variation's
     value (``$aliases`` are kept verbatim for OpenFOAM to expand at run time),
     then drop the ``.template`` suffix and delete the template file,
  3. regenerate ``system/decomposeParDict`` from ``np`` (so the rank count and
     the decomposition can never disagree),
  4. write a ``case_params.json`` sidecar (the parameter vector + metadata),
  5. abort if any unsubstituted ``@!...!@`` token remains.
"""
import datetime
import functools
import json
import os
import re
import shutil
import subprocess

_TOKEN = re.compile(r"@!([A-Z0-9_]+)!@")
_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# Paths whose state can change what a run computes. Deliberately NOT the whole
# tree: docs/**/data churns on every figure regeneration, so a whole-tree
# dirtiness check would mark every run dirty and the flag would mean nothing.
_CODE_PATHS = ("src", "applications", "workflow", "cases", "config")
_IGNORE = shutil.ignore_patterns(
    "processor*", "*.foam", "postProcessing", "*.csv", "log", "log.*",
    "out.*", "err.*", "case_params.json")

# Frozen exact-circle pressure-potential velocity convergence on deterministic
# 10%-perturbed N=32,64,128 meshes is unchanged between 8,16,32,64 corrected
# passes.  Never let a general perturbed-mesh study silently inherit the
# uniform-mesh default of one correction.
_MIN_PERTURBED_NONORTHOGONAL_CORRECTORS = 8


def _render_templates(case_dir, tokens):
    for root, _dirs, files in os.walk(case_dir):
        for f in list(files):
            if not f.endswith(".template"):
                continue
            src = os.path.join(root, f)
            with open(src) as fh:
                text = fh.read()
            for key, val in tokens.items():
                text = text.replace(f"@!{key}!@", str(val))
            with open(os.path.join(root, f[:-len(".template")]), "w") as fh:
                fh.write(text)
            os.remove(src)


@functools.lru_cache(maxsize=1)
def _git_commit():
    """Short commit of the code building this case, ``-dirty`` if any of
    ``_CODE_PATHS`` has uncommitted changes.

    Cached: the commit cannot change within one snakemake invocation, and
    ``materialize`` runs once per variation. Returns "" when this is not a git
    checkout or git is unavailable -- provenance is worth recording, not worth
    failing a study over.

    This is the field that would have caught the phase-2 confusion where
    ``sdplsStability_errors.csv`` reported post-sign-fix numbers while the case
    directories beside it were built before the fix.
    """
    def _git(*args):
        return subprocess.run(("git",) + args, cwd=_REPO, check=True,
                              capture_output=True, text=True).stdout.strip()
    try:
        commit = _git("rev-parse", "--short", "HEAD")
        dirty = _git("status", "--porcelain", "--", *_CODE_PATHS)
    except (OSError, subprocess.CalledProcessError):
        return ""
    return commit + ("-dirty" if dirty else "")


def _write_decompose_par_dict(case_dir, np_):
    """Scotch decomposition: only ``numberOfSubdomains`` is needed -- scotch
    partitions the cell connectivity graph, so there are no per-direction coeffs
    to keep consistent and it works for any ``np`` and any (2D/3D) mesh."""
    text = (
        "/*--------------------------------*- C++ -*"
        "----------------------------------*\\\n"
        f"| generated by the leia Snakemake workflow (np={np_}, scotch)\n"
        "\\*--------------------------------------------------------------------"
        "-------*/\n"
        "FoamFile\n{\n    version     2.0;\n    format      ascii;\n"
        "    class       dictionary;\n    object      decomposeParDict;\n}\n"
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * "
        "* * * //\n\n"
        f"numberOfSubdomains {np_};\n\nmethod          scotch;\n\n"
        "// ********************************************************************"
        "***** //\n")
    system_dir = os.path.join(case_dir, "system")
    os.makedirs(system_dir, exist_ok=True)
    with open(os.path.join(system_dir, "decomposeParDict"), "w") as fh:
        fh.write(text)


def _assert_no_residual_tokens(case_dir):
    bad = []
    for root, _dirs, files in os.walk(case_dir):
        for f in files:
            path = os.path.join(root, f)
            try:
                with open(path, encoding="utf-8", errors="ignore") as fh:
                    if _TOKEN.search(fh.read()):
                        bad.append(os.path.relpath(path, case_dir))
            except OSError:
                continue
    if bad:
        raise RuntimeError(f"[materialize] unsubstituted @!TOKEN!@ remain in: {bad}")


def _with_derived_tokens(tokens):
    """Add tokens that are computed from the sweep values, so templates can use
    them directly:

      * HALF_END_TIME = END_TIME/2 -- controlDict writes a snapshot at maximum
        deformation (t = T/2) as well as t = 0 and t = T (advection studies).
      * DOMAIN_HALF_LENGTH = DOMAIN_LENGTH/2 -- the box centre, so a case that
        centres its droplet in the domain does not hardcode the box size a
        second time in the implicitSurface dict.
      * DROPLET_CENTRE_X = DOMAIN_HALF_LENGTH + DROPLET_OFFSET_X -- the droplet
        centre's x coordinate. DROPLET_OFFSET_X defaults to 0, so this is
        byte-identical to DOMAIN_HALF_LENGTH (same format string) for every study
        that does not set it. It exists so the droplet can be displaced by a
        SUB-CELL amount without restating the box size: sweeping the offset across
        one cell width measures how the curvature estimator's error depends on the
        interface's phase relative to the mesh, which a droplet centred on the box
        can never see because it sits at one fixed phase forever.
      * MAX_DELTA_T uses one of two explicit modes selected by
        TIME_STEP_CONTROL:

          capillary: CAPILLARY_DT_COEFF / nRef^1.5,
                     nRef = CAPILLARY_REF_LENGTH*N_CELLS/DOMAIN_LENGTH
          advective: TARGET_ADVECTIVE_CO*DOMAIN_LENGTH /
                     (N_CELLS*REFERENCE_SPEED)

        The capillary limit is set by the CELL SIZE, dt < sqrt(rho h^3/2 pi
        sigma), NOT by the cell count. CAPILLARY_DT_COEFF was calibrated on the
        0.01 m reference box, where h = L_ref/N_CELLS and the limit reads
        coeff/N_CELLS^1.5. On a truncated (or enlarged) domain N_CELLS no
        longer fixes h, so the formula is evaluated at the reference-EQUIVALENT
        cell count nRef = CAPILLARY_REF_LENGTH/h with h = DOMAIN_LENGTH/N_CELLS.
        This reduces to N_CELLS identically whenever DOMAIN_LENGTH equals
        CAPILLARY_REF_LENGTH, so every pre-existing study is bit-unchanged.

        The capillary mode remains the default for coupled surface-tension runs.
        The advective mode is for sigma=0 kinematic convergence tests, where
        retaining the capillary limit would add progressively more unnecessary
        point-value remaps and confound the spatial study."""
    out = dict(tokens)
    if "END_TIME" in out:
        try:
            out["HALF_END_TIME"] = "{:g}".format(float(out["END_TIME"]) / 2.0)
        except (TypeError, ValueError):
            pass
    if "DOMAIN_LENGTH" in out:
        try:
            out["DOMAIN_HALF_LENGTH"] = "{:.10g}".format(
                float(out["DOMAIN_LENGTH"]) / 2.0
            )
        except (TypeError, ValueError):
            pass
    if "DOMAIN_HALF_LENGTH" in out:
        try:
            out["DROPLET_CENTRE_X"] = "{:.10g}".format(
                float(out["DOMAIN_HALF_LENGTH"])
                + float(out.get("DROPLET_OFFSET_X", 0.0))
            )
        except (TypeError, ValueError):
            pass
    # N_CELLS_BASE: what blockMesh renders on a statically refined hex mesh (mesh:
    # hexRefined). N_CELLS is the capillary-dt handle (below) and on a refined mesh
    # means the FINE spacing, so the base mesh is N_CELLS/2^REFINE_LEVELS. With
    # REFINE_LEVELS 0 (the default) the value is copied VERBATIM, so every existing
    # study renders byte-identically. A non-positive N_CELLS (the poly placeholder
    # -1.0) yields no N_CELLS_BASE at all.
    if "N_CELLS" in out:
        try:
            levels = int(float(out.get("REFINE_LEVELS", 0)))
            n_cells = float(out["N_CELLS"])
        except (TypeError, ValueError) as exc:
            raise RuntimeError(f"[materialize] REFINE_LEVELS/N_CELLS not numeric: {exc}")
        if levels < 0:
            raise RuntimeError(f"[materialize] REFINE_LEVELS must be >= 0, got {levels}")
        if levels == 0:
            out["N_CELLS_BASE"] = out["N_CELLS"]
        elif n_cells > 0:
            n_int, factor = int(round(n_cells)), 2 ** levels
            if n_int % factor:
                raise RuntimeError(
                    f"[materialize] N_CELLS={n_int} is not divisible by 2^REFINE_LEVELS={factor}: "
                    "N_CELLS is the FINE count of the refined mesh and blockMesh needs an "
                    "integer base count")
            out["N_CELLS_BASE"] = str(n_int // factor)
    time_step_control = out.get("TIME_STEP_CONTROL", "capillary")
    if time_step_control == "advective":
        required = (
            "N_CELLS",
            "TARGET_ADVECTIVE_CO",
            "DOMAIN_LENGTH",
            "REFERENCE_SPEED",
        )
        missing = [key for key in required if key not in out]
        if missing:
            raise RuntimeError(
                "[materialize] advective TIME_STEP_CONTROL requires: "
                + ", ".join(missing)
            )
        try:
            n = float(out["N_CELLS"])
            co = float(out["TARGET_ADVECTIVE_CO"])
            length = float(out["DOMAIN_LENGTH"])
            speed = float(out["REFERENCE_SPEED"])
            if n <= 0 or co <= 0 or length <= 0 or speed <= 0:
                raise ValueError("all advective timestep inputs must be positive")
            out["MAX_DELTA_T"] = "{:.10g}".format(co * length / (n * speed))
        except (TypeError, ValueError) as exc:
            raise RuntimeError(f"[materialize] invalid advective timestep: {exc}")
    elif time_step_control == "capillary" and "N_CELLS" in out and "CAPILLARY_DT_COEFF" in out:
        try:
            n = float(out["N_CELLS"])
            coeff = float(out["CAPILLARY_DT_COEFF"])
            # Reference-equivalent cell count: nRef = L_ref/h, h = L/N_CELLS.
            # Identity when DOMAIN_LENGTH == CAPILLARY_REF_LENGTH (or when
            # either token is absent), so existing studies are untouched.
            # FIXED_DELTA_T > 0 overrides the derived step entirely. This exists
            # for one specific experiment: the capillary law ties dt to h as
            # dt ~ h^1.5, so a refinement ladder changes the mesh AND the step
            # together and cannot separate a spatial effect from a per-step one.
            # Measured on the 3D ladder, the growth rate rises 40.5 -> 52.3 -> 90.6
            # 1/s under refinement while r*dt is constant to 24% (4.40, 3.99,
            # 4.94 e-4) -- i.e. the amplification PER STEP does not move and the
            # rate rises only because dt shrinks. Running the same ladder at one
            # FIXED dt decides between the two: equal e-folds means the mechanism
            # is the once-per-step force lag, not resolution.
            fixedDt = out.get("FIXED_DELTA_T")
            useFixed = fixedDt is not None and float(fixedDt) > 0
            nRef = n
            length = out.get("DOMAIN_LENGTH")
            if length is not None:
                length = float(length)
                refLength = float(out.get("CAPILLARY_REF_LENGTH", length))
                if length > 0 and refLength > 0:
                    nRef = refLength*n/length
            if useFixed:
                out["MAX_DELTA_T"] = "{:.6g}".format(float(fixedDt))
            elif nRef > 0:
                out["MAX_DELTA_T"] = "{:.6g}".format(coeff / nRef**1.5)
        except (TypeError, ValueError):
            pass
    elif time_step_control != "capillary":
        raise RuntimeError(
            "[materialize] TIME_STEP_CONTROL must be capillary or advective, got "
            + repr(time_step_control)
        )
    return out


def _reject_yaml_booleans(tokens):
    """Fail fast on a token whose value is a Python bool.

    YAML 1.1 parses the BARE words `off`, `on`, `no`, `yes`, `true` and `false`
    as booleans, so `OSCILLATION: [off]` in a study config arrives here as
    `False` and renders as the string "False". OpenFOAM's Switch is
    case-sensitive and rejects it -- `Expected true/false, on/off... found
    False` -- but only once the solver is already running on a compute node, so
    the mistake costs a whole study's queue time before it surfaces. Measured:
    98 cases across two studies died this way.

    Every value here is destined for a dictionary that OpenFOAM parses as text,
    so a bool is always a quoting accident. Quote it in the config
    (`OSCILLATION: ["off"]`), which is what the existing configs already do for
    REPORT_WRITE_ONLY.
    """
    bad = {k: v for k, v in tokens.items() if isinstance(v, bool)}
    if bad:
        raise RuntimeError(
            "[materialize] token(s) parsed as YAML booleans: "
            + ", ".join(f"{k}={v}" for k, v in sorted(bad.items()))
            + ".\n[materialize] YAML 1.1 reads bare off/on/no/yes/true/false as "
            "booleans; they render as \"False\"/\"True\", which OpenFOAM's Switch "
            "rejects.\n[materialize] Quote the value in the study config, e.g. "
            'OSCILLATION: ["off"].')


def materialize(base_case, tokens, out_dir, np_, mesh, mode, dims, case_name, index):
    _reject_yaml_booleans(tokens)
    tokens = _with_derived_tokens(tokens)
    # The refinement tokens and the mesh kind must agree, or the capillary dt (from
    # N_CELLS) describes a mesh other than the one the study builds.
    try:
        refine_levels = int(float(tokens.get("REFINE_LEVELS", 0)))
    except (TypeError, ValueError) as exc:
        raise RuntimeError(f"[materialize] REFINE_LEVELS not numeric: {exc}")
    if mesh in ("hexRefined", "polyRefined") and refine_levels < 1:
        raise RuntimeError(f"[materialize] mesh: {mesh} needs REFINE_LEVELS >= 1 "
                           f"(got {refine_levels}); set it in axes_override")
    if mesh in ("hex", "perturbed", "poly") and refine_levels != 0:
        raise RuntimeError(f"[materialize] mesh: {mesh} is uniform but REFINE_LEVELS="
                           f"{refine_levels}; use mesh: hexRefined | polyRefined")
        try:
            current = int(tokens["N_NON_ORTHOGONAL_CORRECTORS"])
        except (TypeError, ValueError) as exc:
            raise RuntimeError(
                "[materialize] N_NON_ORTHOGONAL_CORRECTORS must be an integer: "
                + str(exc)
            )
        tokens["N_NON_ORTHOGONAL_CORRECTORS"] = str(
            max(current, _MIN_PERTURBED_NONORTHOGONAL_CORRECTORS)
        )
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    shutil.copytree(base_case, out_dir, ignore=_IGNORE)
    _render_templates(out_dir, tokens)
    _write_decompose_par_dict(out_dir, np_)
    _assert_no_residual_tokens(out_dir)
    meta = {
        "case": case_name, "mesh": mesh, "mode": mode, "np": int(np_),
        "dims": dims, "index": index,
        # Stamped when the case is BUILT, so it describes the code that produced
        # the run rather than whatever is checked out when it is aggregated.
        "gitCommit": _git_commit(),
        "runDate": datetime.datetime.now(
            datetime.timezone.utc).isoformat(timespec="seconds"),
        "tokens": dict(tokens),
    }
    with open(os.path.join(out_dir, "case_params.json"), "w") as fh:
        json.dump(meta, fh, indent=2)
    # ParaView case marker: an empty ``<folderName>.foam`` lets the OpenFOAM
    # reader open this study case directly (File > Open <folderName>.foam).
    # Named after the CASE FOLDER (e.g. 2Dvortex_00009.foam), not the base case:
    # a study materialises many variations of one base case, and identically
    # named stubs make ParaView tabs indistinguishable across variations.
    stub = os.path.basename(os.path.normpath(out_dir))
    open(os.path.join(out_dir, f"{stub}.foam"), "w").close()
    return meta
