#!/usr/bin/env python3
"""Materialize one study variation into a runnable OpenFOAM case directory.

Steps:
  1. copy the template case (``cases/<Case>``) into the study output dir,
  2. render every ``*.template`` by replacing ``@!TOKEN!@`` with the variation's
     value (``$aliases`` are kept verbatim for OpenFOAM to expand at run time),
     then drop the ``.template`` suffix and delete the template file,
  3. regenerate ``system/decomposeParDict`` from ``np`` (so the rank count and
     the decomposition can never disagree),
  4. write a ``case_params.json`` sidecar (the parameter vector + metadata),
  5. abort if any unsubstituted ``@!...!@`` token remains.
"""
import json
import os
import re
import shutil

_TOKEN = re.compile(r"@!([A-Z0-9_]+)!@")
_IGNORE = shutil.ignore_patterns(
    "processor*", "*.foam", "postProcessing", "*.csv", "log", "log.*",
    "out.*", "err.*", "case_params.json")


def _render_templates(case_dir, tokens):
    for root, _dirs, files in os.walk(case_dir):
        for f in list(files):
            if not f.endswith(".template"):
                continue
            src = os.path.join(root, f)
            with open(src) as fh:
                text = fh.read()
            for key, val in tokens.items():
                text = text.replace(f"@!{key}!@", str(val))
            with open(os.path.join(root, f[:-len(".template")]), "w") as fh:
                fh.write(text)
            os.remove(src)


def _write_decompose_par_dict(case_dir, np_):
    """Scotch decomposition: only ``numberOfSubdomains`` is needed -- scotch
    partitions the cell connectivity graph, so there are no per-direction coeffs
    to keep consistent and it works for any ``np`` and any (2D/3D) mesh."""
    text = (
        "/*--------------------------------*- C++ -*"
        "----------------------------------*\\\n"
        f"| generated by the leia Snakemake workflow (np={np_}, scotch)\n"
        "\\*--------------------------------------------------------------------"
        "-------*/\n"
        "FoamFile\n{\n    version     2.0;\n    format      ascii;\n"
        "    class       dictionary;\n    object      decomposeParDict;\n}\n"
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * "
        "* * * //\n\n"
        f"numberOfSubdomains {np_};\n\nmethod          scotch;\n\n"
        "// ********************************************************************"
        "***** //\n")
    system_dir = os.path.join(case_dir, "system")
    os.makedirs(system_dir, exist_ok=True)
    with open(os.path.join(system_dir, "decomposeParDict"), "w") as fh:
        fh.write(text)


def _assert_no_residual_tokens(case_dir):
    bad = []
    for root, _dirs, files in os.walk(case_dir):
        for f in files:
            path = os.path.join(root, f)
            try:
                with open(path, encoding="utf-8", errors="ignore") as fh:
                    if _TOKEN.search(fh.read()):
                        bad.append(os.path.relpath(path, case_dir))
            except OSError:
                continue
    if bad:
        raise SystemExit(f"[materialize] unsubstituted @!TOKEN!@ remain in: {bad}")


def materialize(base_case, tokens, out_dir, np_, mesh, mode, dims, case_name, index):
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    shutil.copytree(base_case, out_dir, ignore=_IGNORE)
    _render_templates(out_dir, tokens)
    _write_decompose_par_dict(out_dir, np_)
    _assert_no_residual_tokens(out_dir)
    meta = {
        "case": case_name, "mesh": mesh, "mode": mode, "np": int(np_),
        "dims": dims, "index": index, "tokens": dict(tokens),
    }
    with open(os.path.join(out_dir, "case_params.json"), "w") as fh:
        json.dump(meta, fh, indent=2)
    return meta
