#!/usr/bin/env python3
"""Generate the TikZ figures of the method-gate test cases (config/gates/methodGate{2D,3D}.yaml).

One tikzpicture per case, with the geometry, the initial condition and the boundary
conditions as the case files define them (cases/<case>/system/*.template, 0.org/*,
src/leiaLevelSet/velocityModel/prescribedVelocityModels.C). The computed geometry --
the 2D shear streamlines (contours of the stream function), the orthographic projection
of the 3D boxes, spheres and spheroids, hidden edges -- comes from this script, so the
figures are regenerated, never edited by hand:

    python3 make_case_figures.py              # writes case_*.tex and tikzstyles.tex here
    python3 make_case_figures.py --preview D  # also writes standalone previews into D

Every label that sits on or next to a line has a white rectangular background.
"""
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

# --------------------------------------------------------------------------- styles
STYLES = r"""% Generated by make_case_figures.py -- do not edit.
\definecolor{gclsWater}{RGB}{198,219,239}
\definecolor{gclsWaterEdge}{RGB}{8,69,148}
\definecolor{gclsAir}{RGB}{252,252,252}
\definecolor{gclsVel}{RGB}{203,24,29}
\definecolor{gclsStream}{RGB}{140,140,140}
\definecolor{gclsWall}{RGB}{90,90,90}
\tikzset{
  gcls/domain/.style={draw=black, line width=0.7pt},
  gcls/hidden/.style={draw=black!50, line width=0.45pt, dash pattern=on 2.4pt off 1.8pt},
  gcls/iface/.style={draw=gclsWaterEdge, line width=1.0pt},
  gcls/ifacehidden/.style={draw=gclsWaterEdge, line width=0.5pt, dash pattern=on 2pt off 1.5pt},
  gcls/ifacefinal/.style={draw=gclsWaterEdge, line width=0.7pt, dash pattern=on 3pt off 2pt},
  gcls/water/.style={fill=gclsWater},
  gcls/lab/.style={fill=white, inner sep=1.3pt, font=\footnotesize},
  gcls/labs/.style={fill=white, inner sep=1.1pt, font=\scriptsize},
  gcls/bc/.style={fill=white, inner sep=1.4pt, font=\footnotesize, align=center},
  gcls/ic/.style={fill=white, draw=black!35, line width=0.3pt, inner sep=2.2pt,
                  font=\footnotesize, align=left, rounded corners=1pt},
  gcls/dim/.style={draw=black!80, line width=0.4pt, {Stealth[length=3pt]}-{Stealth[length=3pt]}},
  gcls/dimone/.style={draw=black!80, line width=0.4pt, -{Stealth[length=3pt]}},
  gcls/vel/.style={draw=gclsVel, line width=0.7pt, -{Stealth[length=3.6pt]}},
  gcls/stream/.style={draw=gclsStream, line width=0.4pt},
  gcls/wallhatch/.style={pattern=north east lines, pattern color=gclsWall!70},
  gcls/axis/.style={draw=black, line width=0.5pt, -{Stealth[length=3.2pt]}},
}
"""


def fmt(v):
    return f"{v:.4f}".rstrip("0").rstrip(".") if abs(v) > 1e-12 else "0"


def P(x, y):
    return f"({fmt(x)},{fmt(y)})"


def polyline(points, closed=False):
    s = " -- ".join(P(x, y) for x, y in points)
    return s + (" -- cycle" if closed else "")


# --------------------------------------------------------------------------- 3D projection
class Ortho:
    """Orthographic projection from a camera at azimuth `az` and elevation `el` (degrees):
    v = (cos el cos az, cos el sin az, sin el) points to the camera; the screen right
    vector r = e_z x v/|.|, the screen up vector u = v x r (so z is up on screen). The
    default camera (front, slightly left, above) shows the faces x = 0 (narrow), y = 0 and
    z = L; its front vertical edges stay clear of a droplet at the box centre."""

    def __init__(self, az_deg=-110.0, el_deg=16.0, scale=1.0, origin=(0.0, 0.0)):
        az, el = math.radians(az_deg), math.radians(el_deg)
        v = np.array([math.cos(el) * math.cos(az), math.cos(el) * math.sin(az), math.sin(el)])
        r = np.cross([0.0, 0.0, 1.0], v)
        r /= np.linalg.norm(r)
        u = np.cross(v, r)
        self.R = np.vstack([r, u, v])
        self.s = scale
        self.o = np.array(origin, dtype=float)

    def __call__(self, p):
        q = self.R @ np.asarray(p, dtype=float)
        return (self.s * q[0] + self.o[0], self.s * q[1] + self.o[1])

    def depth(self, p):
        return float((self.R @ np.asarray(p, dtype=float))[2])

    def facing(self, normal):
        return float((self.R @ np.asarray(normal, dtype=float))[2]) > 0


def box_edges(prj, L):
    """(solid, hidden) edge lists of the box [0,Lx]x[0,Ly]x[0,Lz]."""
    Lx, Ly, Lz = L
    V = {(i, j, k): (i * Lx, j * Ly, k * Lz) for i in (0, 1) for j in (0, 1) for k in (0, 1)}
    faces = {  # normal -> vertex keys
        (-1, 0, 0): [(0, j, k) for j in (0, 1) for k in (0, 1)],
        (1, 0, 0): [(1, j, k) for j in (0, 1) for k in (0, 1)],
        (0, -1, 0): [(i, 0, k) for i in (0, 1) for k in (0, 1)],
        (0, 1, 0): [(i, 1, k) for i in (0, 1) for k in (0, 1)],
        (0, 0, -1): [(i, j, 0) for i in (0, 1) for j in (0, 1)],
        (0, 0, 1): [(i, j, 1) for i in (0, 1) for j in (0, 1)],
    }
    visible = {n for n in faces if prj.facing(n)}
    solid, hidden = [], []
    keys = list(V)
    for a in keys:
        for b in keys:
            if a >= b or sum(abs(x - y) for x, y in zip(a, b)) != 1:
                continue
            owners = [n for n, fv in faces.items() if a in fv and b in fv]
            (solid if any(n in visible for n in owners) else hidden).append((V[a], V[b]))
    return solid, hidden, visible


def draw_box(prj, L, part="all"):
    """part = 'hidden' (dashed back edges), 'visible' (edges of the camera-facing faces), or
    'all'. Draw 'hidden', then the interior (droplet), then 'visible': every point of a
    camera-facing face of a convex box is in front of every interior point on its ray."""
    solid, hidden, _ = box_edges(prj, L)
    out = []
    if part in ("hidden", "all"):
        for a, b in hidden:
            out.append(rf"\draw[gcls/hidden] {P(*prj(a))} -- {P(*prj(b))};")
    if part in ("visible", "all"):
        for a, b in solid:
            out.append(rf"\draw[gcls/domain] {P(*prj(a))} -- {P(*prj(b))};")
    return out


def ellipsoid_outline(prj, c, axes, n=180):
    """Silhouette of an axis-aligned ellipsoid: convex hull of its projected surface."""
    from scipy.spatial import ConvexHull
    u = np.linspace(0, 2 * math.pi, 2 * n)
    v = np.linspace(0, math.pi, n)
    pts = []
    for vv in v:
        for uu in u[::3]:
            p = (c[0] + axes[0] * math.cos(uu) * math.sin(vv),
                 c[1] + axes[1] * math.sin(uu) * math.sin(vv),
                 c[2] + axes[2] * math.cos(vv))
            pts.append(prj(p))
    pts = np.array(pts)
    hull = ConvexHull(pts)
    return [tuple(pts[i]) for i in hull.vertices]


def equator(prj, c, axes, n=240):
    """The z = c_z section of the ellipsoid, split into front (visible) and back runs."""
    runs, cur, cur_front = [], [], None
    for k in range(n + 1):
        t = 2 * math.pi * k / n
        p = (c[0] + axes[0] * math.cos(t), c[1] + axes[1] * math.sin(t), c[2])
        front = prj.depth(p) - prj.depth(c) >= 0
        if cur_front is None or front == cur_front:
            cur.append(prj(p))
        else:
            cur.append(prj(p))
            runs.append((cur_front, cur))
            cur = [prj(p)]
        cur_front = front
    runs.append((cur_front, cur))
    return runs


def draw_droplet3D(prj, c, axes, final=None):
    out = []
    hull = ellipsoid_outline(prj, c, axes)
    out.append(rf"\fill[gcls/water] {polyline(hull, closed=True)};")
    for front, pts in equator(prj, c, axes):
        style = "gcls/iface, line width=0.5pt" if front else "gcls/ifacehidden"
        out.append(rf"\draw[{style}] {polyline(pts)};")
    out.append(rf"\draw[gcls/iface] {polyline(hull, closed=True)};")
    if final is not None:
        hullf = ellipsoid_outline(prj, final, axes)
        out.append(rf"\draw[gcls/ifacefinal] {polyline(hullf, closed=True)};")
    return out


def axis_triad(prj, at, length_cm=0.75, labels=("x", "y", "z")):
    """A small x, y, z glyph with its base at the screen point `at` [cm]."""
    out = []
    o = np.array(prj((0.0, 0.0, 0.0)))
    for k, lab in enumerate(labels):
        e = np.zeros(3); e[k] = 1.0
        d = np.array(prj(e)) - o
        d = d / np.linalg.norm(d) * length_cm
        a = at; b = (at[0] + d[0], at[1] + d[1])
        out.append(rf"\draw[gcls/axis] {P(*a)} -- {P(*b)} node[gcls/labs, pos=1.0, anchor={_anchor(a, b)}, inner sep=0.6pt] {{${lab}$}};")
    return out


def _anchor(a, b):
    dx, dy = b[0] - a[0], b[1] - a[1]
    ang = math.degrees(math.atan2(dy, dx))
    for lim, name in ((22.5, "west"), (67.5, "south west"), (112.5, "south"), (157.5, "south east")):
        if -lim <= ang <= lim if lim == 22.5 else False:
            return name
    if -22.5 <= ang <= 22.5: return "west"
    if 22.5 < ang <= 67.5: return "south west"
    if 67.5 < ang <= 112.5: return "south"
    if 112.5 < ang <= 157.5: return "south east"
    if ang > 157.5 or ang < -157.5: return "east"
    if -157.5 <= ang < -112.5: return "north east"
    if -112.5 <= ang < -67.5: return "north"
    return "north west"


def wrap(lines):
    return "\n".join(lines)


# --------------------------------------------------------------------------- 1D stretch
def case_exact1D():
    s = 3.05                                  # cm per unit length, x in [-2, 2]
    X = lambda x: s * x
    hh = 0.32                                 # half height of the strip [cm]
    xi0, xiT = 0.25, 0.25 * math.e
    L = []
    L.append(r"\begin{tikzpicture}")
    L.append(rf"\fill[gclsAir] {P(X(-2), -hh)} rectangle {P(X(2), hh)};")
    L.append(rf"\fill[gcls/water] {P(X(-2), -hh)} rectangle {P(X(xi0), hh)};")
    L.append(rf"\draw[gcls/domain] {P(X(-2), -hh)} rectangle {P(X(2), hh)};")
    L.append(rf"\draw[gcls/iface] {P(X(xi0), -hh)} -- {P(X(xi0), hh)};")
    L.append(rf"\draw[gcls/ifacefinal] {P(X(xiT), -hh)} -- {P(X(xiT), hh)};")
    # stagnation point
    L.append(rf"\fill {P(X(0), 0)} circle (1.3pt);")
    L.append(rf"\node[gcls/labs, anchor=north] at {P(X(0), -hh - 0.05)} {{$x=0$}};")
    # interface labels above the strip
    L.append(rf"\draw[gcls/dimone] {P(X(xi0), hh + 0.55)} -- {P(X(xiT), hh + 0.55)};")
    L.append(rf"\node[gcls/labs, anchor=south] at {P(X(xi0) - 0.05, hh + 0.02)} {{$x_{{\mathrm i}}(0)=0.25$}};")
    L.append(rf"\node[gcls/labs, anchor=south west] at {P(X(xiT) - 0.1, hh + 0.02)} {{$x_{{\mathrm i}}(T)=0.25\,\mathrm e$}};")
    L.append(rf"\node[gcls/labs, anchor=south] at {P(0.5 * (X(xi0) + X(xiT)), hh + 0.6)} {{$x_{{\mathrm i}}(t)=x_{{\mathrm i}}(0)\,e^{{\alpha t}}$}};")
    # velocity arrows below the strip: u = alpha x
    ya = -hh - 0.55
    for x in (-1.75, -1.25, -0.75, 0.75, 1.25, 1.75):
        dx = 0.18 * x
        L.append(rf"\draw[gcls/vel] {P(X(x), ya)} -- {P(X(x + dx), ya)};")
    L.append(rf"\node[gcls/lab, text=gclsVel, anchor=north] at {P(X(0), ya - 0.08)} {{$\mathbf u=\alpha x\,\mathbf e_x,\ \alpha=\SI{{1}}{{\per\second}}$}};")
    # phase signs
    L.append(rf"\node[gcls/labs] at {P(X(-1.0), 0)} {{$\psi<0$}};")
    L.append(rf"\node[gcls/labs] at {P(X(1.3), 0)} {{$\psi>0$}};")
    # boundary conditions at the ends
    L.append(rf"\node[gcls/bc, anchor=east] at {P(X(-2) - 0.08, 0)} {{$\partial_x\psi=0$\\[-1pt]outflow}};")
    L.append(rf"\node[gcls/bc, anchor=west] at {P(X(2) + 0.08, 0)} {{$\partial_x\psi=0$\\[-1pt]outflow}};")
    # axis ticks
    yt = -hh - 1.45
    L.append(rf"\draw[black!70, line width=0.4pt] {P(X(-2), yt)} -- {P(X(2), yt)};")
    for x in (-2, -1, 0, 1, 2):
        L.append(rf"\draw[black!70, line width=0.4pt] {P(X(x), yt - 0.06)} -- {P(X(x), yt + 0.06)} node[gcls/labs, below=2pt] {{${x}$}};")
    L.append(rf"\node[gcls/labs, anchor=west] at {P(X(2) + 0.12, yt)} {{$x$}};")
    # initial condition and exact solution
    L.append(rf"\node[gcls/ic, anchor=north] at {P(X(0), yt - 0.5)} {{$\psi(x,0)=x-x_{{\mathrm i}}(0)$ (signed distance);\ exact: $\psi(x,t)=x\,e^{{-\alpha t}}-x_{{\mathrm i}}(0)$, $|\nabla\psi|=e^{{-\alpha t}}$;\\ $T=\SI{{1}}{{s}}$, no reversal; one cell in $y$ and $z$ (empty patches)}};")
    L.append(r"\end{tikzpicture}")
    return wrap(L)


# --------------------------------------------------------------------------- 2D shear
def _shear_streamlines(levels=(0.2, 0.45, 0.7, 0.9)):
    import contourpy
    n = 601
    x = np.linspace(0, 1, n)
    Xg, Yg = np.meshgrid(x, x)
    F = np.sin(math.pi * Xg) * np.sin(math.pi * Yg)
    gen = contourpy.contour_generator(Xg, Yg, F)
    out = []
    for c in levels:
        for line in gen.lines(c):
            pts = np.asarray(line)
            # counterclockwise order (the flow is counterclockwise for cos > 0)
            area = 0.5 * np.sum(pts[:-1, 0] * pts[1:, 1] - pts[1:, 0] * pts[:-1, 1])
            if area < 0:
                pts = pts[::-1]
            step = max(1, len(pts) // 140)
            out.append(pts[::step])
    return out


def case_shear2D():
    s = 5.2
    xc, yc, R = 0.5, 0.75, 0.15
    L = [r"\begin{tikzpicture}"]
    L.append(rf"\fill[gclsAir] (0,0) rectangle {P(s, s)};")
    for pts in _shear_streamlines():
        k = int(np.argmax(pts[:, 0]))              # rightmost point: the flow goes up there
        pts = np.roll(pts, -k, axis=0)
        P2 = [(s * a, s * b) for a, b in pts]
        L.append(rf"\draw[gcls/stream, postaction={{decorate}}, decoration={{markings, mark=at position 0.03 with {{\arrow[gclsStream]{{Stealth[length=3.6pt]}}}}}}] {polyline(P2, closed=True)};")
    L.append(rf"\fill[gcls/water] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
    L.append(rf"\draw[gcls/iface] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
    L.append(rf"\draw[gcls/domain] (0,0) rectangle {P(s, s)};")
    # centre and radius
    L.append(rf"\fill {P(s * xc, s * yc)} circle (1.1pt);")
    ang = 200
    L.append(rf"\draw[gcls/dimone] {P(s * xc, s * yc)} -- ++({ang}:{fmt(s * R)});")
    L.append(rf"\node[gcls/labs, anchor=south] at {P(s * xc + 0.45 * s * R * math.cos(math.radians(ang)), s * yc + 0.45 * s * R * math.sin(math.radians(ang)) + 0.03)} {{$R$}};")
    L.append(rf"\node[gcls/labs, anchor=west] at {P(s * xc + 0.07, s * yc + 0.05)} {{$\mathbf x_{{\mathrm c}}$}};")
    # ticks and axis labels
    for v, lab in ((0, "0"), (s, "1")):
        L.append(rf"\draw[black!70, line width=0.4pt] {P(v, 0)} -- {P(v, -0.08)} node[gcls/labs, below=1pt] {{${lab}$}};")
        L.append(rf"\draw[black!70, line width=0.4pt] {P(0, v)} -- {P(-0.08, v)} node[gcls/labs, left=1pt] {{${lab}$}};")
    L.append(rf"\node[gcls/labs] at {P(0.5 * s, -0.32)} {{$x$}};")
    L.append(rf"\node[gcls/labs] at {P(-0.34, 0.5 * s)} {{$y$}};")
    # boundary conditions and initial condition below the domain
    L.append(rf"\node[gcls/bc, anchor=north] (bc) at {P(0.5 * s, -0.55)} {{all four sides: $\partial_n\psi=0$, $\mathbf u\cdot\mathbf n=0$}};")
    L.append(rf"\node[gcls/ic, anchor=north] at ($(bc.south) + (0,-0.08)$) {{$\psi(\mathbf x,0)=|\mathbf x-\mathbf x_{{\mathrm c}}|-R$, $\mathbf x_{{\mathrm c}}=(0.5,0.75)$, $R=0.15$;\\ $\mathbf u=\cos(\pi t/T)\,(u_0,v_0)$, $u_0=\sin^2(\pi x)\sin(2\pi y)$,\\ $v_0=-\sin(2\pi x)\sin^2(\pi y)$; $T=\SI{{2}}{{s}}$; grey: streamlines}};")
    L.append(r"\end{tikzpicture}")
    return wrap([l for l in L if l])


# --------------------------------------------------------------------------- 3D shear
def case_shear3D():
    prj = Ortho(az_deg=-70.0, scale=3.15)     # keeps the sphere at (0.35, 0.75, 0.25) clear of the front edges
    L = [r"\begin{tikzpicture}"]
    c, R = (0.35, 0.75, 0.25), 0.15
    L += draw_box(prj, (1, 1, 1), "hidden")
    L += draw_droplet3D(prj, c, (R, R, R))
    L += draw_box(prj, (1, 1, 1), "visible")
    L.append(rf"\fill {P(*prj(c))} circle (1.0pt);")
    xs = [prj((i, j, k))[0] for i in (0, 1) for j in (0, 1) for k in (0, 1)]
    ys = [prj((i, j, k))[1] for i in (0, 1) for j in (0, 1) for k in (0, 1)]
    xmid, ybot = 0.5 * (min(xs) + max(xs)), min(ys)
    L += axis_triad(prj, (min(xs) - 0.75, ybot - 0.05), length_cm=0.6)
    L.append(rf"\node[gcls/labs, anchor=south] at {P(xmid, max(ys) + 0.08)} {{unit cube $[0,1]^3$}};")
    L.append(rf"\node[gcls/bc, anchor=north] (bc) at {P(xmid, ybot - 0.12)} {{$\partial_n\psi=0$ on all faces;\\ $\mathbf u\cdot\mathbf n=0$ on $x,y\in\{{0,1\}}$; $w\neq0$ on $z\in\{{0,1\}}$}};")
    L.append(rf"\node[gcls/ic, anchor=north] at ($(bc.south) + (0,-0.08)$) {{$\psi(\mathbf x,0)=|\mathbf x-\mathbf x_{{\mathrm c}}|-R$, $R=0.15$,\\ $\mathbf x_{{\mathrm c}}=(0.35,0.75,0.25)$; $(u,v)$ as in 2D;\\ $w=\cos(\pi t/T)\,(1-r/R_{{\mathrm s}})^2$, $r=|(x,y)-(0.5,0.5)|$,\\ $R_{{\mathrm s}}=0.5$; reversed at $t=T/2$, $T=\SI{{3}}{{s}}$}};")
    L.append(r"\end{tikzpicture}")
    return wrap(L)


# --------------------------------------------------------------------------- 2D droplets
def _box2D(s, Lmm, walls_hatched=True):
    W = s * Lmm
    L = [rf"\fill[gclsAir] (0,0) rectangle {P(W, W)};"]
    return L, W


def case_stationary2D(oscillating=False):
    Lmm, s = 10.0, 0.52
    W = s * Lmm
    xc, yc, R = 5.0, 5.0, 1.0
    a, b = (1.1, 1.0 / 1.1) if oscillating else (1.0, 1.0)
    L = [r"\begin{tikzpicture}"]
    L.append(rf"\fill[gclsAir] (0,0) rectangle {P(W, W)};")
    if oscillating:
        L.append(rf"\draw[black!45, line width=0.4pt, dash pattern=on 1.5pt off 1.5pt] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
        L.append(rf"\fill[gcls/water, opacity=0.95] {P(s * xc, s * yc)} ellipse ({fmt(s * a)} and {fmt(s * b)});")
        L.append(rf"\draw[gcls/iface] {P(s * xc, s * yc)} ellipse ({fmt(s * a)} and {fmt(s * b)});")
        L.append(rf"\draw[black!45, line width=0.4pt, dash pattern=on 1.5pt off 1.5pt] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
        # semi-axes
        L.append(rf"\draw[gcls/dimone] {P(s * xc, s * yc)} -- {P(s * (xc + a), s * yc)};")
        L.append(rf"\draw[gcls/dimone] {P(s * xc, s * yc)} -- {P(s * xc, s * (yc + b))};")
        L.append(rf"\node[gcls/labs, anchor=west] at {P(s * (xc + a) + 0.06, s * yc)} {{$a$}};")
        L.append(rf"\node[gcls/labs, anchor=south] at {P(s * xc, s * (yc + b) + 0.05)} {{$b$}};")
    else:
        L.append(rf"\fill[gcls/water] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
        L.append(rf"\draw[gcls/iface] {P(s * xc, s * yc)} circle ({fmt(s * R)});")
        L.append(rf"\draw[gcls/dimone] {P(s * xc, s * yc)} -- ++(35:{fmt(s * R)});")
        L.append(rf"\node[gcls/labs, anchor=south west] at {P(s * xc + s * R * 0.82, s * yc + s * R * 0.55)} {{$R$}};")
    L.append(rf"\fill {P(s * xc, s * yc)} circle (1.0pt);")
    L.append(rf"\draw[gcls/domain] (0,0) rectangle {P(W, W)};")
    # phases, with a leader line from the droplet
    e = (s * (xc + a * math.cos(math.radians(-50))), s * (yc + b * math.sin(math.radians(-50))))
    L.append(rf"\draw[black!60, line width=0.35pt] {P(*e)} -- {P(s * 7.3, s * 2.6)};")
    L.append(rf"\node[gcls/labs, anchor=north west] at {P(s * 7.3 - 0.05, s * 2.6 + 0.02)} {{$\Omega_1$: water}};")
    L.append(rf"\node[gcls/labs] at {P(s * 2.2, s * 1.4)} {{$\Omega_2$: air}};")
    # wall BCs
    L.append(rf"\node[gcls/bc, anchor=north] at {P(0.5 * W, -0.1)} {{walls: $\mathbf u=\mathbf 0$ (no slip),\ $\partial_n p=\partial_n\alpha=\partial_n\psi=0$}};")
    # dimensions
    L.append(rf"\draw[gcls/dim] {P(0, W + 0.28)} -- {P(W, W + 0.28)} node[gcls/labs, midway] {{$L=\SI{{10}}{{mm}}$}};")
    # IC box
    if oscillating:
        ic = (r"$\mathbf u(\mathbf x,0)=\mathbf 0$, $p=0$\\ $\psi(\mathbf x,0)$: signed distance to the ellipse\\"
              r" $a=1.1R$, $b=R/1.1$, $ab=R^2$, $R=\SI{1}{mm}$\\ dashed: the circle of radius $R$")
    else:
        ic = (r"$\mathbf u(\mathbf x,0)=\mathbf 0$, $p=0$\\ $\psi(\mathbf x,0)=|\mathbf x-\mathbf x_{\mathrm c}|-R$\\"
              r" $\mathbf x_{\mathrm c}=(L/2,L/2)$, $R=\SI{1}{mm}$")
    L.append(rf"\node[gcls/ic, anchor=north west] at {P(0.14, W - 0.14)} {{{ic}}};")
    L.append(r"\end{tikzpicture}")
    return wrap(L)


def case_translating2D():
    Lmm, s = 10.0, 0.47
    W = s * Lmm
    x0, y0, R, U0T = 2.5, 5.0, 1.0, 5.0
    L = [r"\begin{tikzpicture}"]
    L.append(rf"\fill[gclsAir] (0,0) rectangle {P(W, W)};")
    L.append(rf"\draw[gcls/ifacefinal] {P(s * (x0 + U0T), s * y0)} circle ({fmt(s * R)});")
    L.append(rf"\fill[gcls/water] {P(s * x0, s * y0)} circle ({fmt(s * R)});")
    L.append(rf"\draw[gcls/iface] {P(s * x0, s * y0)} circle ({fmt(s * R)});")
    L.append(rf"\fill {P(s * x0, s * y0)} circle (1.0pt);")
    L.append(rf"\draw[gcls/vel] {P(s * (x0 + R) + 0.12, s * y0)} -- {P(s * (x0 + U0T - R) - 0.12, s * y0)};")
    yd = s * (y0 + R) + 0.32
    L.append(rf"\draw[black!60, line width=0.3pt] {P(s * x0, s * (y0 + R) + 0.04)} -- {P(s * x0, yd + 0.1)};")
    L.append(rf"\draw[black!60, line width=0.3pt] {P(s * (x0 + U0T), s * (y0 + R) + 0.04)} -- {P(s * (x0 + U0T), yd + 0.1)};")
    L.append(rf"\draw[gcls/dim] {P(s * x0, yd)} -- {P(s * (x0 + U0T), yd)} node[gcls/labs, midway] {{$U_0T=\SI{{5}}{{mm}}$}};")
    L.append(rf"\node[gcls/labs, anchor=north] at {P(s * (x0 + U0T), s * (y0 - R) - 0.05)} {{$t=T$}};")
    L.append(rf"\node[gcls/labs, anchor=north] at {P(s * x0, s * (y0 - R) - 0.05)} {{$t=0$}};")
    L.append(rf"\draw[gcls/domain] (0,0) rectangle {P(W, W)};")
    # inlet arrows
    for yy in (1.5, 3.5, 6.5, 8.5):
        L.append(rf"\draw[gcls/vel] {P(-0.62, s * yy)} -- {P(-0.06, s * yy)};")
    L.append(rf"\node[gcls/bc, rotate=90, anchor=south] at {P(-0.7, 0.5 * W)} {{inlet: $\mathbf u=U_0\mathbf e_x$, $\alpha=0$,\\ $\partial_n p=\partial_n\psi=0$}};")
    L.append(rf"\node[gcls/bc, rotate=-90, anchor=south] at {P(W + 0.1, 0.5 * W)} {{outlet: $p=0$,\\ $\partial_n\mathbf u=\partial_n\alpha=\partial_n\psi=0$}};")
    slip = r"slip: $\mathbf u\cdot\mathbf n=0$, $\partial_n(\mathbf u\cdot\mathbf t)=0$,\\ $\partial_n p=\partial_n\alpha=\partial_n\psi=0$"
    L.append(rf"\node[gcls/bc, anchor=north] at {P(0.5 * W, -0.1)} {{{slip}}};")
    L.append(rf"\node[gcls/bc, anchor=south] at {P(0.5 * W, W + 0.1)} {{{slip}}};")
    ic = (r"$\mathbf u(\mathbf x,0)=U_0\mathbf e_x$, $U_0=\SI{0.05}{m/s}$\\ $\psi(\mathbf x,0)=|\mathbf x-\mathbf x_{\mathrm c}|-R$\\"
          r" $\mathbf x_{\mathrm c}=(L/2-\SI{2.5}{mm},L/2)$")
    L.append(rf"\node[gcls/ic, anchor=north west] at {P(0.14, W - 0.14)} {{{ic}}};")
    L.append(rf"\node[gcls/labs, anchor=south east] at {P(W - 0.12, 0.12)} {{$L=\SI{{10}}{{mm}}$, $T=\SI{{0.1}}{{s}}$}};")
    L.append(r"\end{tikzpicture}")
    return wrap(L)


# --------------------------------------------------------------------------- 3D droplets
def case_droplet3D(kind):
    Lmm = 6.0
    prj = Ortho(scale=0.53 if kind == "translating" else 0.6)
    c = (3.0, 3.0, 3.0)
    if kind == "oscillating":
        axes = (1.1, 1.0 / math.sqrt(1.1), 1.0 / math.sqrt(1.1))
    else:
        axes = (1.0, 1.0, 1.0)
    L = [r"\begin{tikzpicture}"]
    L += draw_box(prj, (Lmm, Lmm, Lmm), "hidden")
    final = (c[0] + 1.0, c[1], c[2]) if kind == "translating" else None
    L += draw_droplet3D(prj, c, axes, final=final)
    L += draw_box(prj, (Lmm, Lmm, Lmm), "visible")
    L.append(rf"\fill {P(*prj(c))} circle (0.9pt);")
    xs = [prj((i, j, k))[0] for i in (0, 6) for j in (0, 6) for k in (0, 6)]
    ys = [prj((i, j, k))[1] for i in (0, 6) for j in (0, 6) for k in (0, 6)]
    xmid, ybot, ytop = 0.5 * (min(xs) + max(xs)), min(ys), max(ys)
    L += axis_triad(prj, (min(xs) - 0.25, ybot + 0.05))
    if kind == "translating":
        for (yy, zz) in ((1.2, 4.8), (4.8, 1.2), (4.8, 4.8), (3.0, 3.0)):   # (1.2, 1.2) would cross the axis glyph
            a = prj((-1.4, yy, zz)); b = prj((-0.08, yy, zz))
            L.append(rf"\draw[gcls/vel] {P(*a)} -- {P(*b)};")
        a_mid = prj((-1.4, 3.0, 3.0))
        L.append(rf"\node[gcls/labs, anchor=east] at {P(a_mid[0] - 0.05, a_mid[1])} {{inlet}};")
        f_out = prj((6.0, 3.0, 3.0))
        right = max(xs)
        L.append(rf"\node[gcls/labs, anchor=west, align=left] at {P(right + 0.08, f_out[1])} {{outlet\\($x=L$, back)}};")
        bc = (r"inlet $x=0$: $\mathbf u=U_0\mathbf e_x$, $\alpha=0$, $\partial_n p=0$;\\ outlet $x=L$: $p=0$,"
              r" $\partial_n\mathbf u=\partial_n\alpha=0$;\\ slip on $y,z\in\{0,L\}$;\\ $\partial_n\psi=0$ on all faces")
        ic = r"$\mathbf u(\mathbf x,0)=U_0\mathbf e_x$, $U_0=\SI{0.05}{m/s}$,\\ $T=\SI{0.02}{s}$; dashed: $t=T$ ($U_0T=R$)"
    else:
        bc = r"walls: $\mathbf u=\mathbf 0$ (no slip),\\ $\partial_n p=\partial_n\alpha=\partial_n\psi=0$"
        if kind == "oscillating":
            ic = (r"$\mathbf u(\mathbf x,0)=\mathbf 0$; prolate spheroid,\\ $\psi(\mathbf x,0)$ its signed distance;\\"
                  r" $a=1.1R$ along $x$, $b=c=R/\sqrt{1.1}$;\\ $abc=R^3$, $T=\SI{0.025}{s}$")
        else:
            ic = (r"$\mathbf u(\mathbf x,0)=\mathbf 0$, $\psi(\mathbf x,0)=|\mathbf x-\mathbf x_{\mathrm c}|-R$;\\"
                  r" $\mathbf x_{\mathrm c}=(L/2,L/2,L/2)$, $T=\SI{0.025}{s}$")
    L.append(rf"\node[gcls/bc, anchor=north] (bc) at {P(xmid, ybot - 0.12)} {{{bc}}};")
    L.append(rf"\node[gcls/ic, anchor=north] at ($(bc.south) + (0,-0.08)$) {{{ic}}};")
    L.append(rf"\node[gcls/labs, anchor=south] at {P(xmid, ytop + 0.08)} {{$L=\SI{{6}}{{mm}}$, $R=\SI{{1}}{{mm}}$}};")
    L.append(r"\end{tikzpicture}")
    return wrap(L)


CASES = {
    "case_exact1D": case_exact1D,
    "case_shear2D": case_shear2D,
    "case_shear3D": case_shear3D,
    "case_stationary2D": lambda: case_stationary2D(False),
    "case_oscillating2D": lambda: case_stationary2D(True),
    "case_translating2D": case_translating2D,
    "case_stationary3D": lambda: case_droplet3D("stationary"),
    "case_translating3D": lambda: case_droplet3D("translating"),
    "case_oscillating3D": lambda: case_droplet3D("oscillating"),
}

PREVIEW = r"""\documentclass[border=4pt]{standalone}
\usepackage{amsmath,amssymb,siunitx}
\usepackage{tikz}
\usetikzlibrary{arrows.meta,decorations.markings,patterns,calc}
\begin{document}
\input{tikzstyles.tex}
\input{%s.tex}
\end{document}
"""


def main(argv):
    with open(os.path.join(HERE, "tikzstyles.tex"), "w") as fh:
        fh.write(STYLES)
    for name, fn in CASES.items():
        with open(os.path.join(HERE, f"{name}.tex"), "w") as fh:
            fh.write(f"% Generated by make_case_figures.py -- do not edit.\n{fn()}\n")
    if "--preview" in argv:
        d = argv[argv.index("--preview") + 1]
        os.makedirs(d, exist_ok=True)
        for name in CASES:
            with open(os.path.join(d, f"preview_{name}.tex"), "w") as fh:
                fh.write(PREVIEW % name)
    print(f"[figures] wrote {len(CASES)} case figures and tikzstyles.tex into {HERE}")


if __name__ == "__main__":
    main(sys.argv[1:])
