#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Processes the cases from the convergence study. 
# Assembles case-specific TaylorCouette.csv into a global convergence CSV file.
# Plots convergence rates for all the schemes used across mesh resolutions as pdf.
python ../plot_study.py --folder-pattern corrected --data-file TaylorCouette.csv
