#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Packs secondary data 
FOLDER_PATTERN=$1
tar -czf $1.tgz $1_00*/TaylorCouette.csv $1_00*/PyFoam*
