#!/usr/bin/env bash
# etc/leia-stamp.sh <library-source-dir> <library-name>
#
# Writes <library-source-dir>/leiaStamp_<library-name>.C, a one-object translation
# unit that registers the library's name and the `git describe --always` of the
# tree it is built from (plus "-dirty" when any of src, applications, workflow,
# cases or config has uncommitted changes -- the same rule as the gitCommit column
# that workflow/scripts/materialize.py stamps into every case). The file is written
# only when the stamp changed, so wmake recompiles it exactly then. Every solver
# prints the registered stamps in its banner and writes them to <case>/leia.version
# (src/leiaLevelSet/leiaVersionRegistry.H). Called by Allwmake before each wmake;
# the generated file is git-ignored (leiaStamp_*.C).
set -u
dir="${1:?library source dir}"; name="${2:?library name}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
describe="$(git -C "$root" describe --always 2>/dev/null || echo unknown)"
dirty=""
[ -n "$(git -C "$root" status --porcelain -- src applications workflow cases config 2>/dev/null)" ] && dirty="-dirty"
stamp="${describe}${dirty}"
out="$root/$dir/leiaStamp_${name}.C"
content="// Generated by etc/leia-stamp.sh -- do not edit, do not commit (git-ignored).
#include \"leiaVersionRegistry.H\"
static const Foam::leia::versionRegistrar leiaStamp_${name}(\"lib${name}\", \"${stamp}\");"
if [ ! -f "$out" ] || [ "$(cat "$out")" != "$content" ]; then
    printf '%s\n' "$content" > "$out"; echo "leia-stamp: lib${name} ${stamp} (written)"
else
    echo "leia-stamp: lib${name} ${stamp} (unchanged)"
fi
