#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -f err.* out.* *.csv *.vtk log log.* 2>/dev/null
rm -f system/blockMeshDict system/controlDict system/fvSchemes system/fvSolution
cleanCase0

#------------------------------------------------------------------------------
