#!/usr/bin/env bash

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions


set -e

changeEndTimeAndDeltaT(){
  local newTime="$1"

  sed -i -E "s/^(endTime[[:space:]]*)[0-9]+(\.[0-9]+)?;/\1${newTime};/" system/controlDict
  sed -i -E "s/^(deltaT[[:space:]]*)[0-9]+(\.[0-9]+)?;/\1${newTime};/" system/controlDict
  sed -i -E "s/^(writeInterval[[:space:]]*)[0-9]+(\.[0-9]+)?;/\1${newTime};/" system/controlDict
}

myRestore0Dir(){
  rm -rf 0 
  cp -r 0.org 0
}

echo 
echo "Restoring 0 directory" 
myRestore0Dir

runApplication blockMesh


# # Case1 : from Paper with sharp IC
# echo 
# echo "Running case 1" 
# changeEndTimeAndDeltaT 1

# runApplication -s case1 setFields 
# runApplication -s case1 leiaTestRedistance
# mv 1 1_store

# # Case 2: Use setAlphaFields and normalize data
# echo 
# echo "Running case 2" 
# myRestore0Dir
# changeEndTimeAndDeltaT 2

# runApplication -s case2 setAlphaField

# activation="minMax"
# sed -i -E \
#   's/(word activation \(")[^"]+("\);)/\1'"$activation"'\2/' \
#   system/initLevelSet

# postProcess -func "initLevelSet"
# runApplication -s case2 leiaTestRedistance 
# mv 2 2_store


# Case 3: Use setAlphaFields and normalize data. 
# This is the one that works best

echo 
echo "Running case 3" 
myRestore0Dir
changeEndTimeAndDeltaT 3

# Start from sharp field
runApplication -s case3 setFields

# Apply tanh smoothing 
activation="tanh"
sed -i -E \
  's/(word activation \(")[^"]+("\);)/\1'"$activation"'\2/' \
  system/initLevelSet

postProcess -func "initLevelSet"
runApplication -s case3 leiaTestRedistance 


mv 1_store 1 
mv 2_store 2

touch a.foam



