#!/usr/bin/env bash

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

rm -rf 0 
cp -r 0.org 0

runApplication blockMesh
runApplication setFields
runApplication leiaTestRedistance
