name: Build Tests
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Build-OpenFOAM-v2206-Opt:
    runs-on: ubuntu-latest
    container: tmaric/openfoam-v2206_ubuntu-focal
    defaults:
        run:
            shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build with OpenFOAM-v2206 in Opt mode
        run: ls /opt/OpenFOAM && . /opt/OpenFOAM/OpenFOAM-v2206/etc/bashrc && ./Allwmake
